
Couldn't find a valid proxy.

Preprocessing:   0%|          | 0/10 [00:00<?, ?file/s]Preprocessing:  10%|#         | 1/10 [00:15<02:22, 15.88s/file]Preprocessing:  20%|##        | 2/10 [00:17<00:58,  7.32s/file]Preprocessing:  30%|###       | 3/10 [00:17<00:28,  4.10s/file]Preprocessing:  40%|####      | 4/10 [00:17<00:15,  2.53s/file]Preprocessing:  50%|#####     | 5/10 [00:18<00:09,  1.86s/file]Preprocessing:  60%|######    | 6/10 [00:18<00:05,  1.38s/file]Preprocessing:  80%|########  | 8/10 [00:18<00:01,  1.37file/s]Preprocessing:  90%|######### | 9/10 [00:26<00:02,  2.56s/file]Preprocessing: 100%|##########| 10/10 [00:27<00:00,  2.21s/file]Preprocessing: 100%|##########| 10/10 [00:27<00:00,  2.79s/file]
Processing:   0%|          | 0/38 [00:00<?, ?chunk/s]Processing:   3%|2         | 1/38 [00:46<28:51, 46.80s/chunk]Processing:   5%|5         | 2/38 [00:53<14:02, 23.41s/chunk]Processing:   8%|7         | 3/38 [01:00<09:05, 15.58s/chunk]Processing:  11%|#         | 4/38 [01:00<05:25,  9.57s/chunk]Processing:  13%|#3        | 5/38 [01:01<03:36,  6.57s/chunk]Processing:  16%|#5        | 6/38 [01:27<06:54, 12.95s/chunk]Processing:  18%|#8        | 7/38 [01:41<06:53, 13.33s/chunk]Processing:  21%|##1       | 8/38 [01:43<04:54,  9.83s/chunk]Processing:  24%|##3       | 9/38 [01:54<04:59, 10.32s/chunk]Processing:  26%|##6       | 10/38 [01:56<03:31,  7.56s/chunk]Processing:  29%|##8       | 11/38 [02:09<04:06,  9.14s/chunk]Processing:  32%|###1      | 12/38 [02:35<06:12, 14.33s/chunk]Processing:  34%|###4      | 13/38 [02:36<04:16, 10.24s/chunk]Processing:  37%|###6      | 14/38 [02:45<04:03, 10.14s/chunk]Processing:  39%|###9      | 15/38 [02:46<02:49,  7.37s/chunk]Processing:  39%|###9      | 15/38 [02:48<04:19, 11.26s/chunk]
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/cvmfs/sft.cern.ch/lcg/releases/Python/3.6.5-f74f0/x86_64-centos7-gcc8-opt/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/var/lib/condor/execute/dir_3346/site-packages/coffea/processor/executor.py", line 197, in __call__
    out = self.function(*args, **kwargs)
  File "/var/lib/condor/execute/dir_3346/site-packages/coffea/processor/executor.py", line 990, in automatic_retries
    raise e
  File "/var/lib/condor/execute/dir_3346/site-packages/coffea/processor/executor.py", line 978, in automatic_retries
    return func(*args, **kwargs)
  File "/var/lib/condor/execute/dir_3346/site-packages/coffea/processor/executor.py", line 1167, in _work_function
    else uproot.MultithreadedFileSource,
  File "/var/lib/condor/execute/dir_3346/site-packages/uproot/reading.py", line 154, in open
    **options  # NOTE: a comma after **options breaks Python 2
  File "/var/lib/condor/execute/dir_3346/site-packages/uproot/reading.py", line 590, in __init__
    file_path, **self._options  # NOTE: a comma after **options breaks Python 2
  File "/var/lib/condor/execute/dir_3346/site-packages/uproot/source/xrootd.py", line 273, in __init__
    self._open()
  File "/var/lib/condor/execute/dir_3346/site-packages/uproot/source/xrootd.py", line 276, in _open
    self._resource = XRootDResource(self._file_path, self._timeout)
  File "/var/lib/condor/execute/dir_3346/site-packages/uproot/source/xrootd.py", line 84, in __init__
    self._open()
  File "/var/lib/condor/execute/dir_3346/site-packages/uproot/source/xrootd.py", line 93, in _open
    self._xrd_error(status)
  File "/var/lib/condor/execute/dir_3346/site-packages/uproot/source/xrootd.py", line 116, in _xrd_error
    raise uproot._util._file_not_found(self._file_path, status.message)
FileNotFoundError: file not found ([ERROR] Server responded with an error: [3022] invalid argument
)

    'root://xrootd-cms.infn.it//store/mc/RunIISummer20UL17NanoAODv9/QCD_HT1500to2000_TuneCP5_PSWeights_13TeV-madgraph-pythia8/NANOAODSIM/106X_mc2017_realistic_v9-v1/260000/A24117CA-FEB5-A34D-80A5-27BBBDDB0142.root'

Files may be specified as:
   * str/bytes: relative or absolute filesystem path or URL, without any colons
         other than Windows drive letter or URL schema.
         Examples: "rel/file.root", "C:\abs\file.root", "http://where/what.root"
   * str/bytes: same with an object-within-ROOT path, separated by a colon.
         Example: "rel/file.root:tdirectory/ttree"
   * pathlib.Path: always interpreted as a filesystem path or URL only (no
         object-within-ROOT path), regardless of whether there are any colons.
         Examples: Path("rel:/file.root"), Path("/abs/path:stuff.root")

Functions that accept many files (uproot.iterate, etc.) also allow:
   * glob syntax in str/bytes and pathlib.Path.
         Examples: Path("rel/*.root"), "/abs/*.root:tdirectory/ttree"
   * dict: keys are filesystem paths, values are objects-within-ROOT paths.
         Example: {"/data_v1/*.root": "ttree_v1", "/data_v2/*.root": "ttree_v2"}
   * already-open TTree objects.
   * iterables of the above.

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 51, in <module>
    executor_args={'schema': NanoAODSchema,'workers':  options.workers},
  File "/var/lib/condor/execute/dir_3346/site-packages/coffea/processor/__init__.py", line 107, in _run_x_job
    processor_instance=processor_instance,
  File "/var/lib/condor/execute/dir_3346/site-packages/coffea/processor/executor.py", line 1366, in __call__
    wrapped_out = executor(chunks, closure, None)
  File "/var/lib/condor/execute/dir_3346/site-packages/coffea/processor/executor.py", line 579, in __call__
    return processwith(pool=poolinstance)
  File "/var/lib/condor/execute/dir_3346/site-packages/coffea/processor/executor.py", line 569, in processwith
    accumulator,
  File "/var/lib/condor/execute/dir_3346/site-packages/coffea/processor/accumulator.py", line 94, in accumulate
    accum = iadd(accum, next(gen))
  File "/var/lib/condor/execute/dir_3346/site-packages/coffea/processor/accumulator.py", line 86, in <genexpr>
    gen = (x for x in items if x is not None)
  File "/var/lib/condor/execute/dir_3346/site-packages/tqdm/std.py", line 1167, in __iter__
    for obj in iterable:
  File "/var/lib/condor/execute/dir_3346/site-packages/coffea/processor/executor.py", line 240, in _futures_handler
    yield done.pop().result()
  File "/cvmfs/sft.cern.ch/lcg/releases/Python/3.6.5-f74f0/x86_64-centos7-gcc8-opt/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/cvmfs/sft.cern.ch/lcg/releases/Python/3.6.5-f74f0/x86_64-centos7-gcc8-opt/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
FileNotFoundError: file not found ([ERROR] Server responded with an error: [3022] invalid argument
)

    'root://xrootd-cms.infn.it//store/mc/RunIISummer20UL17NanoAODv9/QCD_HT1500to2000_TuneCP5_PSWeights_13TeV-madgraph-pythia8/NANOAODSIM/106X_mc2017_realistic_v9-v1/260000/A24117CA-FEB5-A34D-80A5-27BBBDDB0142.root'

Files may be specified as:
   * str/bytes: relative or absolute filesystem path or URL, without any colons
         other than Windows drive letter or URL schema.
         Examples: "rel/file.root", "C:\abs\file.root", "http://where/what.root"
   * str/bytes: same with an object-within-ROOT path, separated by a colon.
         Example: "rel/file.root:tdirectory/ttree"
   * pathlib.Path: always interpreted as a filesystem path or URL only (no
         object-within-ROOT path), regardless of whether there are any colons.
         Examples: Path("rel:/file.root"), Path("/abs/path:stuff.root")

Functions that accept many files (uproot.iterate, etc.) also allow:
   * glob syntax in str/bytes and pathlib.Path.
         Examples: Path("rel/*.root"), "/abs/*.root:tdirectory/ttree"
   * dict: keys are filesystem paths, values are objects-within-ROOT paths.
         Example: {"/data_v1/*.root": "ttree_v1", "/data_v2/*.root": "ttree_v2"}
   * already-open TTree objects.
   * iterables of the above.

ls: cannot access hists/UL_BFF_v1_test_v3_2017/QCD_HT1500to2000_TuneCP5_PSWeights_13TeV-madgraph-pythia8____2_.futures: No such file or directory
cp: cannot stat 'hists/UL_BFF_v1_test_v3_2017/QCD_HT1500to2000_TuneCP5_PSWeights_13TeV-madgraph-pythia8____2_.futures': No such file or directory
